
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: Build@1
  displayName: Build package
  script: |
    dotnet build --configuration $(buildConfiguration)

- task: Build@2
  displayName: Prepare native libtorch
    curl -O https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
    unzip libtorch-shared-with-deps-latest.zip

- task: Test@1
  displayName: Run Tests
    LD_LIBRARY_PATH=`pwd`/libtorch/lib dotnet test Test --configuration Release --logger trx

- task: Publish@1
  displayName: dotnet publish artifacts
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

