################################################################################
# TorchSharp's PR validation build
################################################################################

resources:
  containers:
#   - container: CentosContainer
#     image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-8bba86b-20190314145033
  
   - container: UbuntuContainer
     image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-20200515184230-2c829e8

jobs:
- template: /build/ci/job-template.yml
  parameters:
    name: Ubuntu_x64_NetCoreApp30
    prepScript: (wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -) && sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" && sudo apt-get -y update && sudo apt-get -y install clang-6.0 git cmake libunwind8 curl libssl1.0.0 libomp-dev
    buildScript: ./build.sh build /p:SkipCuda=true -c 
    testScript: ./build.sh test /p:SkipCuda=true -c 
    pool:
      name: Hosted Ubuntu 1604
    container: UbuntuContainer

- template: /build/ci/job-template.yml
  parameters:
    prepScript: brew update && brew install libomp && brew install llvm && brew install mono-libgdiplus gettext && brew link gettext --force && brew link libomp --force && brew link llvm --force
    name: MacOS_x64_NetCoreApp30
    buildScript: ./build.sh build /p:SkipCuda=true -c 
    testScript: ./build.sh test /p:SkipCuda=true -c 
    pool:
      name: Hosted macOS

- template: /build/ci/job-template.yml
  parameters:
    prepScript: echo "no prep needed"
    name: Windows_x64_NetCoreApp30
    buildScript: build.cmd  build  /p:SkipCuda=true -c 
    testScript: build.cmd test /p:SkipCuda=true -c 
    pool:
      name: Hosted VS2017

################################################################################
# {Build} --> combine --> package to build native bits on multiple OS's
################################################################################


################################################################################
- job: Linux_Build_For_Package
################################################################################
  variables:
    BuildConfig: Release
    OfficialBuildId: $(BUILD.BUILDNUMBER)
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_MULTILEVEL_LOOKUP: 0
    TORCHSHARP_MAKING_PACKAGE: 1
  pool:
    name: Hosted Ubuntu 1604
  container: UbuntuContainer
  steps:
  - script: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - script: sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
  - script: sudo apt-get -y update
  - script: sudo apt-get -y install clang-6.0 git cmake libunwind8 curl libssl1.0.0 libomp-dev
  - script: ./build.sh build -c $(BuildConfig) 
    displayName: Build

  - task: PublishBuildArtifacts@1
    displayName: Publish Linux package assets
    inputs:
      pathToPublish: $(Build.SourcesDirectory)/bin/obj/Release/packages
      artifactName: PackageAssets
      artifactType: container

################################################################################
- job: MacOS_Build_For_Package
################################################################################
  variables:
    BuildConfig: Release
    OfficialBuildId: $(BUILD.BUILDNUMBER)
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_MULTILEVEL_LOOKUP: 0
    TORCHSHARP_MAKING_PACKAGE: 1
  pool:
    name: Hosted macOS
  steps:
  - script: brew update && brew install libomp && brew install llvm && brew install mono-libgdiplus gettext && brew link gettext --force && brew link libomp --force && brew link llvm --force
    displayName: Install build dependencies (macOS)
  - script: ls -Flas /usr/local/opt/llvm/bin/
    displayName: Debug Stuff
  - script: ./build.sh build -c $(BuildConfig)
    displayName: Build

  - task: PublishBuildArtifacts@1
    displayName: Publish macOS package assets
    inputs:
      pathToPublish: $(Build.SourcesDirectory)/bin/obj/Release/packages
      artifactName: PackageAssets
      artifactType: container


################################################################################
- job: Package
################################################################################
  dependsOn:
  - Linux_Build_For_Package
  - MacOS_Build_For_Package
  variables:
    BuildConfig: Release
    OfficialBuildId: $(BUILD.BUILDNUMBER)
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_MULTILEVEL_LOOKUP: 0
  pool:
    name: Hosted VS2017	
  steps:

  # Download all agent packages from all previous jobs
  - task: DownloadBuildArtifacts@0
    displayName: Download package assets
    inputs:
      artifactName: PackageAssets
      downloadPath: $(Build.SourcesDirectory)/..
      parallelizationLimit: 1

  # Workaround https://github.com/Microsoft/vsts-tasks/issues/6739
  - task: CopyFiles@2
    displayName: Copy package assets to correct folder
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/../PackageAssets
      targetFolder: $(Build.SourcesDirectory)/../
  
  # remove to free up space
  - script: rmdir /s /q $(Build.SourcesDirectory)/../PackageAssets
    displayName: Create Packages

  # build the windows bits including CUDA support
  - script: build.cmd pack -c Release 
    displayName: Create Packages

  - task: CopyFiles@2
    displayName: Copy packaged assets to staging folder
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/bin/packages/Release
      targetFolder: $(Build.ArtifactStagingDirectory)
 
  #  - script: |
  #      cp $(Build.SourcesDirectory)\bin\obj\packages\Release\*.nupkg $BUILD_ARTIFACTSTAGINGDIRECTORY
  #    # rm $BUILD_ARTIFACTSTAGINGDIRECTORY/*.symbols.nupkg
  #    displayName: Copy Nugets in staging directory

  #  - script: |
  #      dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  #    displayName: Dotnet Publish

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), ne(variables['system.pullrequest.isfork'], true))
  
  # Terminate all dotnet build processes.
  - script: $(Build.SourcesDirectory)/Tools/dotnetcli/dotnet.exe build-server shutdown
    displayName: Dotnet Server Shutdown
